services:
  - type: web
    name: persian-translator
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn translation_bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 